routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('index');
});


Route::resource('empresas', 'EmpresaController');

Route::resource('linhas', 'LinhaController');

Route::resource('indicadores', 'IndicadorController');

Route::resource('xml', 'XmlController');

resources/views/empresa_form.blade.php
@extends('principal')

@section('conteudo')

@if ($acao == 1)
    <form method="post" action="{{route('empresas.store')}}">
@else
    <form method="post" action="{{route('empresas.update', $reg->id)}}">
    {!! method_field('put') !!}
@endif
        {{ csrf_field() }}

    <div class="col-sm-4">
        <label for="cnpj">CNPJ: </label>
        <input class="form-control input-lg" id="cnpj" type="text" name="cnpj" value="{{$reg->cnpj or old('cnpj')}}">
    </div>

    <div class="col-sm-6">
        <label for="razao_social">Razão Social: </label>
        <input class="form-control input-lg" id="razao_social" type="text" name="razao_social" value="{{$reg->razao_social or old('razao_social')}}">
    </div>

    <div class="col-sm-10">
        <button type="submit" class="btn btn-danger">Salvar Empresa</button>
    </div>
</form>

@endsection

resources/views/empresa_show.blade.php
@extends('principal')

@section('conteudo')

<div class='col-sm-11'>
    <h2>Cadastro de Empresas</h2>
</div>

<div class='col-sm-1'>
    <a href="{{route('empresas.create')}}" class="btn btn-danger" role="button">Nova Empresa</a>
</div>

<div class='col-sm-12'>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Cód</th>
                <th>CNPJ</th>
                <th>Razão_Social</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>

            @foreach($empresas as $empresa)

            <tr>
                <td>{{$empresa->id}}</td>
                <td>{{$empresa->cnpj}}</td>
                <td>{{$empresa->razao_social}}</td>
                
                <td>
                    <a href="{{route('empresas.edit', $empresa->id)}}" class="btn btn-success" role="button">Editar</a>
                    <form style="display: inline-block;"
                          method="POST"
                          action="{{route('empresas.destroy', $empresa->id)}}"
                          onsubmit="return confirm('Confirmar Exclusão ?')">
                        {{method_field('DELETE')}}
                        {{csrf_field()}}
                        <button type="submit" class="btn btn-danger">Excluir</button>
                    </form>

                </td>

            </tr>

            @endforeach
        </tbody>
    </table>
</div>



@endsection

resources/views/index.blade.php
@extends('principal')

@section('conteudo')


<div class='col-sm-12'>
    <h1> Bem-Vindo ao Gerador de XML AGERGS </h1>
</div>

<div class='col-sm-12'>
    <h5> Desenvolvido por : Renato Silva </h5>
</div>

<div class='col-sm-3'>
    <h5> <a href="https://www.facebook.com/RenaatoSiilva"><img src='imagens/Facebook.png' alt='Facebook'></a> </h5>
</div>


<div class='col-sm-3'>
    <h5> <a href="mailto:renato_silva94@live.com"><img src='imagens/Email.png' alt='Email'></a> </h5>
</div>

<div class='col-sm-3'>
    <h5> <a href="https://twitter.com/RenaatoSiilva"><img src='imagens/Twitter.png' alt='Twitter'></a> </h5>
</div>

<div class='col-sm-3'>
    <h5> <a href="https://www.instagram.com/renatosilva94/"><img src='imagens/Instagram.png' alt='Instagram'></a> </h5>
</div>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Anuncio 2 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-8588473675874247"
     data-ad-slot="4555546430"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


@endsection

resources/views/indicador_show.blade.php
@extends('principal')

@section('conteudo')

<div class='col-sm-11'>
    <h2>Cadastro de Indicadores</h2>
</div>

<div class="col-sm-6">



    <div class='col-sm-3'>
        <a href="{{route('indicadores.create')}}" class="btn btn-primary" role="button">Novo Indicador</a>

    </div>

</div>




<div class='col-sm-12'>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Cód</th>
                <th>Viagens_Realizadas</th>
                <th>Viagens_Programadas</th>
                <th>Viagens_Impontuais</th>
                <th>Viagens_Interrompidas</th>
                <th>Ocorrencia_Quebra</th>
                <th>Desvio_Itinerario</th>
                <th>Viagens_Abaixo_80</th>
                <th>Viagens_Acima_80</th>
                <th>Viagens_100</th>
                <th>Acidentes_Transito</th>
                <th>Ações</th>

            </tr>
        </thead>
        <tbody>

            @foreach($indicadores as $indicador)

            <tr>
                <td>{{$indicador->id}}</td>
                <td>{{$indicador->viagens_realizadas}}</td>
                <td>{{$indicador->viagens_programadas}}</td>
                <td>{{$indicador->viagens_impontuais}}</td>
                <td>{{$indicador->viagens_interrompidas}}</td>
                <td>{{$indicador->ocorrencia_quebra}}</td>
                <td>{{$indicador->desvio_itinerario}}</td>
                <td>{{$indicador->viagens_abaixo_80}}</td>
                <td>{{$indicador->viagens_acima_80}}</td>
                <td>{{$indicador->viagens_100}}</td>
                <td>{{$indicador->acidentes_transito}}</td>












                <td>
                    <a href="{{route('indicadores.edit', $indicador->id)}}" class="btn btn-success" role="button">Editar</a>
                    <form style="display: inline-block;" method="POST" action="{{route('indicadores.destroy', $indicador->id)}}"
                          onsubmit="return confirm('Confirmar Exclusão ?')">
                        {{method_field('DELETE')}}
                        {{csrf_field()}}
                        <button type="submit" class="btn btn-danger">Excluir</button>


                    </form>

                    <a href="{{route('xml.index')}}" class="btn btn-primary">Gerar XML</a>

                </td>

            </tr>

            @endforeach
        </tbody>
    </table>
</div>

@endsection

resources/views/linha_form.blade.php
@extends('principal')

@section('conteudo')

@if ($acao == 1)
<form method="post" action="{{route('linhas.store')}}">
    @else
    <form method="post" action="{{route('linhas.update', $reg->id)}}">
        {!! method_field('put') !!}
        @endif
        {{ csrf_field() }}

       
        
        <div class="col-sm-4">
            <label for="cod_linha">Cód Linha: </label>
            <input class="form-control input-lg" id="cod_linha" type="text" name="cod_linha" value="{{$reg->cod_linha or old('cod_linha')}}">
        </div>

        <div class="col-sm-6">
            <label for="nome_linha">Nome de Linha: </label>
            <input class="form-control input-lg" id="nome_linha" type="text" name="nome_linha" value="{{$reg->nome_linha or old('nome_linha')}}">
        </div>

        <div class="col-sm-2">
            <label for="modalidade">Modalidade:</label>
            <select class="form-control" id="combustivel" name="modalidade">
                <option value="CM"
                        @if ((isset($reg) and $reg->modalidade == "Comum") or 
                        old('modalidade') == "CM") selected @endif                        
                        >Comum</option>
               <option value="DI"
                        @if ((isset($reg) and $reg->modalidade == "Direto") or 
                        old('modalidade') == "DI") selected @endif                        
                        >Direto</option>
               <option value="SD"
                        @if ((isset($reg) and $reg->modalidade == "SemiDireto") or 
                        old('modalidade') == "SD") selected @endif                        
                        >SemiDireto</option>
                 <option value="IO"
                        @if ((isset($reg) and $reg->modalidade == "Integração ônibus") or 
                        old('modalidade') == "IO") selected @endif                        
                        >Integração ônibus</option>
                 <option value="RT"
                        @if ((isset($reg) and $reg->modalidade == "Rota") or 
                        old('modalidade') == "RT") selected @endif                        
                        >Rota</option>
                 <option value="IT"
                        @if ((isset($reg) and $reg->modalidade == "Integração Trem") or 
                        old('modalidade') == "IT") selected @endif                        
                        >Integração Trem</option>
                 <option value="ST"
                        @if ((isset($reg) and $reg->modalidade == "Seletivo") or 
                        old('modalidade') == "ST") selected @endif                        
                        >Seletivo</option>
                 <option value="EX"
                        @if ((isset($reg) and $reg->modalidade == "Executivo") or 
                        old('modalidade') == "EX") selected @endif                        
                        >Executivo</option>
                 
                 
                 
            </select>
        </div>

        <div class="col-sm-10">
            <button type="submit" class="btn btn-danger">Salvar Empresa</button>
        </div>
    </form>

    @endsection

resources/views/linha_show.blade.php
@extends('principal')

@section('conteudo')

<div class='col-sm-11'>
    <h2>Cadastro de Linhas</h2>
</div>

<div class="col-sm-6">

    <div class='col-sm-3'>
        <a href="{{route('linhas.create')}}" class="btn btn-danger" role="button">Nova Linha</a>

    </div>

 

</div>




<div class='col-sm-12'>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Cód</th>
                <th>Cod_Linha</th>
                <th>Nome_Linha</th>
                <th>Modalidade</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>

            @foreach($linhas as $linha)

            <tr>
                <td>{{$linha->id}}</td>
                <td>{{$linha->cod_linha}}</td>
                <td>{{$linha->nome_linha}}</td>
                <td>{{$linha->modalidade}}</td>


                <td>
                    <a href="{{route('linhas.edit', $linha->id)}}" class="btn btn-success" role="button">Editar</a>
                    <form style="display: inline-block;" method="POST" action="{{route('linhas.destroy', $linha->id)}}"
                          onsubmit="return confirm('Confirmar Exclusão ?')">
                        {{method_field('DELETE')}}
                        {{csrf_field()}}
                        <button type="submit" class="btn btn-danger">Excluir</button>


                    </form>



                </td>

            </tr>

            @endforeach
        </tbody>
    </table>
</div>



@endsection

resources/views/principal.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AGERGS - XML</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Agergs XML</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{{url('/')}}">Página Inicial</a></li>
      <li><a href="{{route('empresas.index')}}">Empresa</a></li>
      <li><a href="{{route('linhas.index')}}">Linha</a></li>
      <li><a href="{{route('indicadores.index')}}">Indicador</a></li>
    </ul>
  </div>
</nav>
  
<div class="container">
  @yield('conteudo')
</div>

</body>
</html>

resources/views/xml.blade.php
@extends('principal')

@section('conteudo')

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<textarea class="form-control" style="height:600px; width:1000px" id="download">
<?php echo'<?xml version="1.0" encoding="UTF-8"?>'?>

<carga_dados>
    @foreach ($empresas as $empresa)   
    @foreach($indicadores as $indicador)
    <cnpj>{{$empresa->cnpj}}</cnpj>
    <razao_social>{{$empresa->razao_social}}</razao_social>
    <mes_ano>{{$indicador->mes_ano}}</mes_ano>
    @endforeach
    @endforeach
    <carga_linha>
        @foreach($linhas as $linha)
        <cod_linha>{{$linha->cod_linha}}</cod_linha>
        <nome_linha>{{$linha->nome_linha}}</nome_linha>
        <modalidade>{{$linha->modalidade}}</modalidade>
        @endforeach
        <carga_indicador>
            @foreach($indicadores as $indicador)
            <id_indicador>301</id_indicador>
            <cod_precisao>{{$indicador->icpoPrecisao}}</cod_precisao>
            <val_indicador>{{$indicador->icpo}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>302</id_indicador>
            <cod_precisao>{{$indicador->viagensrealizadasPrecisao}}</cod_precisao>
            <val_indicador>{{$indicador->viagens_realizadas}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>303</id_indicador>
            <cod_precisao>{{$indicador->viagensprogramadasPrecisao}}</cod_precisao>
            <val_indicador>{{$indicador->viagens_programadas}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>304</id_indicador>
            <cod_precisao>{{$indicador->iphsPrecisao}}</cod_precisao>
            <val_indicador>{{$indicador->iphs}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>305</id_indicador>
            <cod_precisao>{{$indicador->viagensimpontuaisPrecisao}}</cod_precisao>
            <val_indicador>{{$indicador->viagens_impontuais}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>306</id_indicador>
            <cod_precisao>{{$indicador->icviPrecisao}}</cod_precisao>
            <val_indicador>{{$indicador->icvi}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>307</id_indicador>
            <cod_precisao>{{$indicador->viagensinterrompidasPrecisao}}</cod_precisao>
            <val_indicador>{{$indicador->viagens_interrompidas}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>308</id_indicador>
            <cod_precisao>{{$indicador->imfuPrecisao}}</cod_precisao>
            <val_indicador>{{$indicador->imfu}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>309</id_indicador>
            <cod_precisao>{{$indicador->ioqPrecisao}}</cod_precisao>
            <val_indicador>{{$indicador->ioq}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>310</id_indicador>
            <cod_precisao>{{$indicador->idiPrecisao}}</cod_precisao>
            <val_indicador>{{$indicador->idi}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>311</id_indicador>
            <cod_precisao>{{$indicador->io1Precisao}}</cod_precisao>
            <val_indicador>{{$indicador->io1}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>312</id_indicador>
            <cod_precisao>{{$indicador->io2Precisao}}</cod_precisao>
            <val_indicador>{{$indicador->io2}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>313</id_indicador>
            <cod_precisao>{{$indicador->io3Precisao}}</cod_precisao>
            <val_indicador>{{$indicador->io3}}</val_indicador>
        </carga_indicador>
        <carga_indicador>
            <id_indicador>314</id_indicador>
            <cod_precisao>{{$indicador->ioapPrecisao}}</cod_precisao>
            <val_indicador>{{$indicador->ioap}}</val_indicador>
            @endforeach
        </carga_indicador>
    </carga_linha>
</carga_dados>
</textarea>

<button class="btn btn-success">Efetuar Download</button>

<script>
$("button").click(function () {
// create `a` element
$("<a />", {
// if supported , set name of file
//download: $.now() + ".txt",
download: {{$empresa -> cnpj}} + "-ITM-" + {{$indicador->ano_mes}} + ".xml",
        // set `href` to `objectURL` of `Blob` of `textarea` value
        href: URL.createObjectURL(
                new Blob([$("textarea").val()], {
                type: "text/plain"
                }))
        })
        // append `a` element to `body`
        // call `click` on `DOM` element `a`
        .appendTo("body")[0].click();
// remove appended `a` element after "Save File" dialog,
// `window` regains `focus` 
$(window).one("focus", function () {
$("a").last().remove()
        })
})</script>

@endsection